# Please see the following page for more information: https://webauthn-doc.spomky-labs.com/the-webauthn-server/the-symfony-way#configuration

webauthn:
    credential_repository: 'App\Repository\PublicKeyCredentialSourceRepository'
    user_repository: 'App\Repository\UserKeyRepository'
    creation_profiles:
        default:
            rp:
                name: '%env(RELAYING_PARTY_NAME)%'
                id: '%env(RELAYING_PARTY_ID)%'
    request_profiles:
        default:
            rp_id: '%env(RELAYING_PARTY_ID)%'
